id = "imba"
name = "Imba"
version = "0.0.1"
schema_version = 1
authors = ["Heap Void"]
description = "Imba language support for Zed"
repository = "https://github.com/HeapVoid/imba-lsp"
languages = ["languages/imba"]

[lib]
kind = "Rust"
version = "0.7.0"

[language_servers.imba-lsp]
name = "Imba LSP"
language = "Imba"

[grammars.imba]
repository = "https://github.com/HeapVoid/imba-lsp"
rev = "8d6d5a487071f301b9606337980e9b29c01423da"
