id = "imba"
name = "Imba"
version = "0.0.1"
schema_version = 1
authors = ["Fedor"]
description = "Imba language support for Zed"
repository = "https://github.com/imba/imba-lsp"

[grammars.imba]
repository = "file:///Users/fedor/Projects/modules/imba-lsp"
rev = "9c130531455ed59dc9c4b20620f9558be5d22e1a"
